spring.application.name=han
spring.datasource.url=jdbc:h2:file:./han_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
server.port=8081
groq.api.key=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
